DATA CHECKING

In [1]:
import pandas as pd
import statsmodels.formula.api as smf
from scipy import stats

freq = pd.read_csv("freMTPL2freq.csv") 
sev = pd.read_csv("freMTPL2sev.csv")

In [2]:
freq.head()

,IDpol,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Area,Density,Region
0,1,1,0.10,5,0,55,50,B12,Regular,D,1217,Rhone-Alpes
1,3,1,0.77,5,0,55,50,B12,Regular,D,1217,Rhone-Alpes
2,5,1,0.75,6,2,52,50,B12,Diesel,B,54,Picardie
3,10,1,0.09,7,0,46,50,B12,Diesel,B,76,Aquitaine
4,11,1,0.84,7,0,46,50,B12,Diesel,B,76,Aquitaine

In [3]:
sev.head()

     IDpol  ClaimAmount
0     1552       995.20
1  1010996      1128.12
2  4024277      1851.11
3  4007252      1204.00
4  4046424      1204.00

In [4]:
freq.shape

(678013, 12)

In [5]:
sev.shape

(26639, 2)

In [10]:
freq.isna().sum()

IDpol         0
ClaimNb       0
Exposure      0
VehPower      0
VehAge        0
DrivAge       0
BonusMalus    0
VehBrand      0
VehGas        0
Area          0
Density       0
Region        0
dtype: int64

In [11]:
sev.isna().sum()

IDpol          0
ClaimAmount    0
dtype: int64

In [12]:
freq.duplicated().sum()

np.int64(0)

In [15]:
sev.duplicated().sum()

np.int64(255)

Frequency

In [18]:
total_policies = len(freq)
total_exposure = freq["Exposure"].sum()
total_claims = freq["ClaimNb"].sum()

overall_frequency = total_claims / total_exposure

print("Policies:", total_policies)
print("Exposure:", total_exposure)
print("Claims:", total_claims)
print("Claim frequency:", overall_frequency)

Policies: 678013
Exposure: 358499.44546217704
Claims: 36102
Claim frequency: 0.10070308464063966

Severity

In [19]:
total_loss = sev["ClaimAmount"].sum()
average_severity = sev["ClaimAmount"].mean()
median_severity = sev["ClaimAmount"].median()

print("Total Loss:", total_loss)
print("Mean Severity:", average_severity)
print("Median Severity:", median_severity)

Total Loss: 60697930.68000001
Mean Severity: 2278.5363819963213
Median Severity: 1172.0